matches:
  
  - trigger: "aoa"
    replace: "السلام عليكم ورحمة الله وبركاته"
    word: true

  - trigger: "ws"
    replace: "وعلیکم السلام ورحمتہ اللہ وبرکاتہ"
    word: true

  - trigger: ":think"
    replace: "🤔"
  
  - trigger: ":sad"
    replace: "😔"

  - trigger: ":tired"
    replace: "🫩"
  
  - trigger: "->"
    replace: "→"

  - trigger: "<-"
    replace: "←"

  - trigger: "ia"
    word: true
    replace: "InshaAllah"
