matches:
  
  - trigger: "aoa"
    replace: "السلام عليكم ورحمة الله وبركاته"
    word: true

  - trigger: ":think"
    replace: "🤔"
  
  - trigger: "->"
    replace: "→"

  - trigger: "<-"
    replace: "←"
